### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [bdemers/maven-wrapper#3]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/org/apache/maven/wrapper/PathAssembler.java: Line number => 70: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/org/apache/maven/wrapper/PathAssembler.java: Line number => 73: API name => MessageDigest:<BR>

**Comment by bdemers** [comment]
@mhp0rtal Thanks for the report. You may want to report this issue against https://github.com/takari/maven-wrapper
